#!/bin/bash

# Function to check if rofi is already installed
check_rofi_installed() {
    # Check if the rofi executable exists in PATH
    command -v rofi >/dev/null 2>&1
}

# Check if rofi is already installed
if check_rofi_installed; then
    echo "rofi is already installed."
    exit 0
fi

# Create a temporary directory
temp_dir=$(mktemp -d)
cd "$temp_dir" || exit

# Install dependencies
sudo emerge --ask --autounmask-write bison flex ninja meson cmake libxcb-xkb libxcb-util libxkbcommon libxcb-ewmh libxcb-icccm libxcb-randr libxcb-util libxcb-xinerama libxkbcommon libxcb-cursor libstartup-notification zip
sudo dispatch-conf

# Download and install rofi for Wayland
git clone https://github.com/lbonn/rofi.git ~/sway/rofi

cd ~/sway/rofi || exit
meson setup build && ninja -C build
sudo ninja -C build install

# Clean up
cd ~ || exit
rm -rf "$temp_dir"

echo "rofi installed successfully."
