#!/bin/bash

# Simple script to handle a DIY shutdown menu. When run, you should see a bunch of options (shutdown, reboot, etc.)
#
# Requirements:
# - rofi
# - OpenRC
#
# Instructions:
# - Save this file as power.sh or anything
# - Give it exec privilege, with `chmod +x /path/to/power.sh`
# - Run it

chosen=$(echo -e "[Cancel]\nLogout\nShutdown\nReboot\nSuspend\nHibernate\nHybrid-sleep\nSuspend-then-hibernate" | rofi -dmenu -i)

if [[ $chosen = "Logout" ]]; then
    pkill dwm
elif [[ $chosen = "Shutdown" ]]; then
    poweroff
elif [[ $chosen = "Reboot" ]]; then
    reboot
elif [[ $chosen = "Suspend" ]]; then
    # Suspend command might vary; this is a common one
    pm-suspend
elif [[ $chosen = "Hibernate" ]]; then
    # Hibernate command might vary; this is a common one
    pm-hibernate
elif [[ $chosen = "Hybrid-sleep" ]]; then
    # Hybrid-sleep command might vary; this is a common one
    pm-hybrid
elif [[ $chosen = "Suspend-then-hibernate" ]]; then
    # Suspend-then-hibernate command might vary; this is a common one
    pm-suspend && pm-hibernate
fi
